import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  contentContainer: {
    alignItems: "center",
    justifyContent: "flex-start",
    padding: 16,
  },
  profileContainer: {
    flex: 1,
    backgroundColor: "#f8f9fa",
  },
  contentContainerWithMargin: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    borderColor: "#ccc",
    borderStyle: "solid",
    borderWidth: 1,
    margin: 16,
  },
  formRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 5,
    gap: 10,
    fontWeight: "bold",
  },
  errorMessage: {
    color: "red",
    fontWeight: "bold",
    borderRadius: 5,
    fontSize: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginVertical: 8,
  },
  subtitle: {
    fontSize: 18,
    marginBottom: 12,
    color: "#666",
  },
  body: {
    fontSize: 16,
    lineHeight: 24,
    textAlign: "left",
  },
  input: {
    width: "100%",
    padding: 10,
    marginVertical: 8,
    backgroundColor: "#fff",
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 4,
    fontSize: 16,
  },
  inputForm: {
    padding: 8,
    marginVertical: 8,
    backgroundColor: "#fff",
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 8,
    fontSize: 16,
  },
  inputTitle: {
    fontSize: 16,
  },
  button: {
    fontSize: 16,
    backgroundColor: "#2c2c2c",
    paddingHorizontal: 64,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 8,
  },
  profileHeader: {
      alignItems: "center",
      padding: 20,
      position: "relative",
  },
  backButton: {
      position: "absolute",
      top: 10,
      left: 10,
      paddingVertical: 8,
      paddingHorizontal: 12,
      backgroundColor: "#E2E8F0",
      borderRadius: 20,
      zIndex: 1,
  },
  backButtonText: {
      color: "#2D3748",
      fontWeight: "600",
  },
  editTitle: {
      fontSize: 24,
      fontWeight: "bold",
      color: "#2D3748",
      marginBottom: 20,
  },
  profilePicture: {
      width: 80,
      height: 80,
      borderRadius: 40,
      marginBottom: 5,
  },
  userKudos: {
      fontSize: 18,
      color: "#718096",
      marginBottom: 15,
  },
  feedbackContainer: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      backgroundColor: "#C6F6D5",
      borderRadius: 20,
      marginTop: 10,
  },
  feedbackText: {
      color: "#2F855A",
      fontWeight: "600",
  },
  editFormContainer: {
      backgroundColor: "#fff",
      borderRadius: 10,
      paddingHorizontal: 20,
      paddingVertical: 25,
      marginHorizontal: 15,
      marginBottom: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
  },
  inputContainer: {
      marginBottom: 20,
  },
  inputLabel: {
      fontSize: 16,
      fontWeight: "600",
      color: "#4A5568",
      marginBottom: 8,
  },
  avatarEditContainer: {
      marginBottom: 25,
  },
  uploadButton: {
      backgroundColor: "#3182CE",
      paddingVertical: 12,
      borderRadius: 8,
      alignItems: "center",
      marginTop: 10,
      marginBottom: 15,
  },
  uploadButtonText: {
      color: "#FFF",
      fontSize: 16,
      fontWeight: "600",
  },
  orText: {
      fontSize: 16,
      color: "#718096",
      textAlign: "center",
      marginVertical: 10,
  },
  updateButton: {
      backgroundColor: "#38A169",
      paddingVertical: 14,
      borderRadius: 8,
      alignItems: "center",
      marginBottom: 15,
  },
  updateButtonText: {
      color: "#FFF",
      fontSize: 16,
      fontWeight: "bold",
  },
  errorText: {
      color: "#E53E3E",
      marginVertical: 10,
      textAlign: "center",
  },
  cancelButton: {
      borderWidth: 1,
      borderColor: "#E53E3E",
      paddingVertical: 14,
      borderRadius: 8,
      alignItems: "center",
  },
  cancelButtonText: {
      color: "#E53E3E",
      fontSize: 16,
      fontWeight: "600",
  },
  userName: {
      fontSize: 32,
      fontWeight: "bold",
      color: "#2D3748",
      marginBottom: 5,
  },
});
