#!/usr/bin/env node
/**
 * Build-time script to discover React components and generate a registry.
 * Run: node scripts/generateComponentRegistry.mjs
 */

import glob from 'glob';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { basename, dirname, relative } from 'path';

const COMPONENTS_DIR = 'src/components';
const OUTPUT_FILE = 'src/generated/componentRegistry.ts';

async function main() {
    // Find all .tsx files in src/components
    const files = glob.sync(`${COMPONENTS_DIR}/**/*.tsx`);

    const components = [];

    for (const file of files) {
        const content = readFileSync(file, 'utf-8');
        const fileName = basename(file, '.tsx');
        const folder = dirname(relative(COMPONENTS_DIR, file)) || 'root';

        // Check if it has a default export (likely a component)
        const hasDefaultExport = /export\s+default\s+(function|class|const)/.test(content) ||
                                  /export\s+\{\s*\w+\s+as\s+default\s*\}/.test(content) ||
                                  /export\s+default\s+\w+/.test(content);

        if (!hasDefaultExport) continue;

        // Skip test files
        if (fileName.includes('.test') || fileName.includes('.spec')) continue;

        // Skip index files that just re-export
        if (fileName === 'index' && content.length < 500) continue;

        // Extract component name from default export
        let componentName = fileName;
        const match = content.match(/export\s+default\s+function\s+(\w+)/);
        if (match) {
            componentName = match[1];
        }

        const importPath = '@/' + relative('src', file).replace('.tsx', '');

        components.push({
            name: componentName,
            fileName,
            folder: folder === '.' ? 'root' : folder,
            path: file,
            importPath
        });
    }

    // Sort by folder then name
    components.sort((a, b) => {
        if (a.folder !== b.folder) return a.folder.localeCompare(b.folder);
        return a.name.localeCompare(b.name);
    });

    // Group by folder
    const byFolder = {};
    for (const comp of components) {
        if (!byFolder[comp.folder]) byFolder[comp.folder] = [];
        byFolder[comp.folder].push(comp);
    }

    // Generate TypeScript file
    const output = `// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/generateComponentRegistry.mjs
// Run: node scripts/generateComponentRegistry.mjs

export interface ComponentInfo {
    name: string;
    fileName: string;
    folder: string;
    path: string;
    importPath: string;
}

export const componentRegistry: ComponentInfo[] = ${JSON.stringify(components, null, 2)};

export const componentsByFolder: Record<string, ComponentInfo[]> = ${JSON.stringify(byFolder, null, 2)};

export const folders = ${JSON.stringify(Object.keys(byFolder).sort(), null, 2)};
`;

    // Ensure directory exists
    const outputDir = dirname(OUTPUT_FILE);
    if (!existsSync(outputDir)) {
        mkdirSync(outputDir, { recursive: true });
    }

    writeFileSync(OUTPUT_FILE, output);
    console.log(`Generated ${OUTPUT_FILE} with ${components.length} components in ${Object.keys(byFolder).length} folders`);
}

main().catch(console.error);
