name: Deploy if tests succeed

on:
  workflow_run:
    workflows: ["E2E Tests"]
    types: [completed]

jobs:
  deploy:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      #github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_repository.full_name == github.repository &&
      (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'dev')
    runs-on: ubuntu-latest

    steps:
      - name: Debug payload
        run: |
          echo "event:        ${{ github.event.workflow_run.event }}"
          echo "name:         ${{ github.event.workflow_run.name }}"
          echo "conclusion:   ${{ github.event.workflow_run.conclusion }}"
          echo "head_branch:  ${{ github.event.workflow_run.head_branch }}"
          echo "head_sha:     ${{ github.event.workflow_run.head_sha }}"
          echo "repo:         ${{ github.event.workflow_run.head_repository.full_name }}"

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Enable Corepack and Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.7.0 --activate

      - name: Install deps
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME }}
          directory: dist
          branch: ${{ github.event.workflow_run.head_branch }}
          wranglerVersion: '3'
