name: Deploy if tests succeed

on:
  workflow_run:
    workflows: ["E2E Tests"]
    types: [completed]

jobs:
  deploy:
    if: >
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'dev') &&
        github.event.workflow_run.head_repository.full_name == github.repository
      }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Enable Corepack and Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.7.0 --activate

      - name: Install deps
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: your-pages-project-name
          directory: dist
          branch: ${{ github.event.workflow_run.head_branch }}
          wranglerVersion: '3'
